# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2017.3/overview/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2017.3/overview/getting_support_for_pe.html#standard-releases-and-long-term-support-releases
# ------------------------------------------------------------------------------
#  release   pup    ruby      eol
# PE 2018.1  5.5.10 2.4.5   2019-??  (LTS)
# PE 2019    6.0.5  2.5.1   ????-??  (LTS)
---
.cache_bundler_r2_4: &cache_bundler_r2_4
  cache:
    untracked: true
    # An attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler_r2_4"
    paths:
      - '.vendor'
      - 'vendor'

.cache_bundler_r2_5: &cache_bundler_r2_5
  cache:
    untracked: true
    # An attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler_r2_5"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - '(find .vendor | wc -l) || :'
    - gem install bundler --no-rdoc --no-ri
    - rm -f Gemfile.lock
    - rm -rf pkg/
    - bundle install --no-binstubs --jobs $(nproc) --path=.vendor "${FLAGS[@]}"

.validation_checks: &validation_checks
  script:
    - bundle exec rake clean
    - bundle exec rake pkg:gem

.spec_tests: &spec_tests
  script:
    - bundle exec rake spec
  # Currently, the spec tests require rpmbuild, which isn't available to might not be on the GitLab Runners
  allow_failure: true

stages:
  - validation
  - unit
  - acceptance
  - deploy


# Puppet 5.5 for PE 2018.1 support
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
# --------------------------------------
pup5.5-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.5.10'
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  <<: *validation_checks

pup5.5-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.5.10'
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  <<: *spec_tests

# Keep an eye on the latest puppet 5
# ----------------------------------
pup5.latest-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.0'
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  <<: *validation_checks

pup5.latest-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.0'
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  <<: *spec_tests

# Keep an eye on puppet 6
# -----------------------
pup6.latest-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.5
  variables:
    PUPPET_VERSION: '~> 6.0'
  <<: *cache_bundler_r2_5
  <<: *setup_bundler_env
  <<: *validation_checks

pup6.latest-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.5
  variables:
    PUPPET_VERSION: '~> 6.0'
  <<: *cache_bundler_r2_5
  <<: *setup_bundler_env
  <<: *spec_tests

# Acceptance tests
# ==============================================================================
acceptance:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '5.5.10'
  script:
    - bundle exec rake acceptance

fips-acceptance:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler_r2_4
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '5.5.10'
    BEAKER_fips: 'yes'
  script:
    - bundle exec rake acceptance
  allow_failure: true
