HOSTS:
  el7-build-server:
    roles:
      - default
      - build_server
    platform: el-7-x86_64
    hypervisor: docker
    image: centos:7
    docker_cmd: '/usr/sbin/sshd -D -E /var/log/sshd.log'
    mount_folders:
      folder1:
        host_path: ./
        container_path: /host_files
    docker_preserve_image: true
    ssh:
      password: root
      auth_methods:
        - password

  el8-build-server:
    roles:
      - build_server
    platform: el-8-x86_64
    hypervisor: docker
    image: centos:8
    docker_cmd: '["/sbin/init"]'
    docker_cap_add:
      - AUDIT_WRITE
    mount_folders:
      folder1:
        host_path: ./
        container_path: /host_files
    docker_preserve_image: true
    ssh:
      password: root
      auth_methods:
        - password

CONFIG:
  log_level: verbose
  type:      aio
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% else -%>
  puppet_collection: puppet6
<% end -%>
