---
HOSTS:
  el7-build-server:
    roles:
      - default
      - build_server
    platform: el-7-x86_64
    hypervisor: docker
    image: simpproject/simp_build_centos7
    docker_cmd: "/usr/sbin/sshd -D -E /var/log/sshd.log"

  el8-build-server:
    roles:
      - build_server
    platform: el-8-x86_64
    hypervisor: docker
    image: simpproject/simp_build_centos8
    docker_cmd: '["/sbin/init"]'
    docker_preserve_image: true

CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet8') %>"
  ssh:
    password: root
    auth_methods:
      - password
  docker_preserve_image: true
  mount_folders:
    host_files:
      host_path: ./
      container_path: /host_files
