HOSTS:
  el6-build-server:
    roles:
      - default
      - master
      - agent
      - build_server
    platform: el-6-x86_64
    hypervisor: docker
    image: centos:6
    docker_image_commands:
      - 'yum install -y epel-release'
      - "echo 'Defaults:build_user !requiretty' >> /etc/sudoers"
      - "echo 'build_user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - 'useradd -b /home -m -c "Build User" -s /bin/bash -U build_user'
      - 'yum install -y facter'
      # simp build-deps
      - 'yum install -y rpm-build augeas-devel createrepo genisoimage git gnupg2 libicu-devel libxml2 libxml2-devel libxslt libxslt-devel rpmdevtools which'
      # rvm build-deps
      - 'yum install -y libyaml-devel glibc-headers autoconf gcc-c++ glibc-devel readline-devel libffi-devel openssl-devel automake libtool bison sqlite-devel'
      - 'runuser build_user -l -c "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"'
      - 'runuser build_user -l -c "curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1"'
      - 'runuser build_user -l -c "rvm use --default 2.1"'
      - 'runuser build_user -l -c "rvm all do gem install bundler"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc simp-rake-helpers"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc rake"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc json"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc charlock_holmes"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc posix-spawn"'
    # NOTE: the './' syntax requires BKR-704
    mount_folders:
      folder1:
        # must be an absolute path, seemingly
        host_path: ./
        container_path: /host_files
    docker_preserve_image: true

  el7-build-server:
    roles:
      - build_server
    platform: el-7-x86_64
    hypervisor: docker
    image: centos:7
    docker_cmd: '/sbin/sshd; tail -f /dev/null'
    docker_image_commands:
      - 'yum install -y epel-release'
      - 'ln -sf /bin/true /usr/bin/systemctl'
      - "echo 'Defaults:build_user !requiretty' >> /etc/sudoers"
      - "echo 'build_user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - 'useradd -b /home -m -c "Build User" -s /bin/bash -U build_user'
      - 'yum install -y facter'
      # simp build-deps
      - 'yum install -y rpm-build augeas-devel createrepo genisoimage git gnupg2 libicu-devel libxml2 libxml2-devel libxslt libxslt-devel rpmdevtools clamav-update which'
      # rvm build-deps
      - 'yum install -y libyaml-devel glibc-headers autoconf gcc-c++ glibc-devel readline-devel libffi-devel openssl-devel automake libtool bison sqlite-devel'
      - 'runuser build_user -l -c "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"'
      - 'runuser build_user -l -c "curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1"'
      - 'runuser build_user -l -c "rvm use --default 2.1"'
      - 'runuser build_user -l -c "rvm all do gem install bundler"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc simp-rake-helpers"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc json"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc charlock_holmes"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc posix-spawn"'
    # NOTE: the './' syntax requires BKR-704
    mount_folders:
      folder1:
        # must be an absolute path, seemingly
        host_path: ./
        container_path: /host_files
    docker_preserve_image: true
    ssh:
      password: root
      auth_methods:
        - password

CONFIG:
  log_level: verbose
  type:      foss
