puppetversion = ENV.key?('PUPPET_VERSION') ? "#{ENV['PUPPET_VERSION']}" : ['~>3']
source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'json', :require => false
gem 'puppet', puppetversion, :require => false

if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion, :require => false
else
  gem 'facter', :require => false
end
