# Run all tests as GitHub Actions
name: Unit Tests
on:
  push:
    branches:
      # A test branch for seeing if your tests will pass in your personal fork
      - test_me_github
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  spec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - 2.4
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rspec
        run: bundle exec rake spec
      - name: gem build
        run: bundle exec rake pkg:install_gem

  acceptance:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: ensure entropy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rng-tools
          sudo systemctl start rng-tools
      - name: install bundler
        run: |
          gem install bundler
          bundle update
      - name: install docker
        run: |
          set -x
          sudo apt-get remove -y docker docker-engine docker.io containerd runc ||:
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update -y
          sudo apt-cache gencaches
          sudo apt-get install -y docker-ce
          sudo systemctl start docker
      - name: beaker
        run: bundle exec rake acceptance
